### ISSUE TITLE
Facts module fails to get interfaces from C1300 - KyeError: -1

### ISSUE THREAD

**Issue by alexandrud** [ansible-collections/community.ciscosmb#79]
##### SUMMARY
Cisco C1300-24T-4G switches use the same SMB IOS as the SG series.
While on one switch the module managed to connect and get the interfaces on other switches it fails.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
facts

##### ANSIBLE VERSION
```
ansible [core 2.17.5]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
Collection         Version
------------------ -------
community.ciscosmb 1.0.9 
```

##### CONFIGURATION
```
ansible-config dump --only-changed
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT
Fedora release 40 (Forty) - ghcr.io/ansible-community/community-ee-base:2.17.5-1

```
sh version
Active-image: flash://system/images/image1.bin
  Version: 4.0.0.91
  MD5 Digest: 5e834beda25a2dd18c3bdfe882a0eb78
  Date: 14-Mar-2023
  Time: 05:36:46
Inactive-image: flash://system/images/_image1.bin
  Version: 4.0.0.91
  MD5 Digest: 5e834beda25a2dd18c3bdfe882a0eb78
  Date: 14-Mar-2023
  Time: 05:36:46
```

##### STEPS TO REPRODUCE
Try to get facts from the switch:

```yaml
- name: IOS-SMB - Get switch info
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_cli_ssh_type: libssh
    ansible_network_os: community.ciscosmb.ciscosmb
    print_data: true
  community.ciscosmb.facts:
    gather_subset:
      - interfaces
      - default
  register: switch_facts

- name: IOS - Print data
  when: print_data == true
  debug:
    msg: "{{ switch_facts }}"

```

##### EXPECTED RESULTS
Get facts from the switch.

##### ACTUAL RESULTS

```
<10.0.171.170> ESTABLISH LOCAL CONNECTION FOR USER: 1000
<10.0.171.170> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /runner/.ansible/tmp/ansible-local-1578jba668t2 `"&& mkdir "` echo /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767 `" && echo ansible-tmp-1732873373.738936-1586-18723976427767="` echo /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767 `" ) && sleep 0'
Using module file /runner/.ansible/collections/ansible_collections/community/ciscosmb/plugins/modules/facts.py
<10.0.171.170> PUT /runner/.ansible/tmp/ansible-local-1578jba668t2/tmpr9r4i6vl TO /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py
<10.0.171.170> EXEC /bin/sh -c 'chmod u+x /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/ /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py && sleep 0'
<10.0.171.170> EXEC /bin/sh -c '/usr/bin/python3 /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py && sleep 0'
<10.0.171.170> EXEC /bin/sh -c 'rm -f -r /runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py", line 107, in <module>
    _ansiballz_main()
  File "/runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/runner/.ansible/tmp/ansible-local-1578jba668t2/ansible-tmp-1732873373.738936-1586-18723976427767/AnsiballZ_facts.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.ciscosmb.plugins.modules.facts', init_globals=dict(_module_fqn='ansible_collections.community.ciscosmb.plugins.modules.facts', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/modules/facts.py", line 768, in <module>
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/modules/facts.py", line 756, in main
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/modules/facts.py", line 407, in populate
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/modules/facts.py", line 658, in populate_neighbors
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/module_utils/ciscosmb.py", line 93, in ciscosmb_parse_table
  File "/tmp/ansible_community.ciscosmb.facts_payload_2didqccz/ansible_community.ciscosmb.facts_payload.zip/ansible_collections/community/ciscosmb/plugins/module_utils/ciscosmb.py", line 150, in __get_table_data
KeyError: -1
```

**Comment by alexandrud** [comment]
Looking through the code and at the error again, this seems to happen when it's trying to parse the LLDP neighbors.

Switch where the module is working:
```
show lldp neigh

System capability legend:
B - Bridge; R - Router; W - Wlan Access Point; T - telephone;
D - DOCSIS Cable Device; H - Host; r - Repeater;
TP - Two Ports MAC Relay; S - S-VLAN; C - C-VLAN; O - Other

  Port        Device ID          Port ID         System Name    Capabilities  TTL  
--------- ----------------- ----------------- ----------------- ------------ ----- 
gi3       78:45:aa:15:fa:89 78:45:01:a5:fa:89 somename      H        97                                    
gi7       20:c6:eb:aa:62:2a 20:c6:eb:ef:62:2a                        O        108  
gi8       20:c6:eb:aa:51:e2 20:c6:eb:ef:51:e2                        O        109 
```

Switches where the module fails:
```
show lldp neigh  

System capability legend:
B - Bridge; R - Router; W - Wlan Access Point; T - telephone;
D - DOCSIS Cable Device; H - Host; r - Repeater;
TP - Two Ports MAC Relay; S - S-VLAN; C - C-VLAN; O - Other

  Port        Device ID          Port ID         System Name    Capabilities  TTL  
--------- ----------------- ----------------- ----------------- ------------ ----- 
gi1          QXN4100162           ETH1                                        113 
```

**Comment by qaxi** [comment]
Hello, good point.

Could you do quick test with line https://github.com/ansible-collections/community.ciscosmb/blob/main/plugins/modules/facts.py#L658 changed to 
`neighbor_table = ciscosmb_parse_table(tables[0], allow_empty_fields=[3,4])` to allow empty "Capabilities" field?

**Comment by alexandrud** [comment]
> Hello, good point.
> 
> Could you do quick test with line https://github.com/ansible-collections/community.ciscosmb/blob/main/plugins/modules/facts.py#L658 changed to `neighbor_table = ciscosmb_parse_table(tables[0], allow_empty_fields=[3,4])` to allow empty "Capabilities" field?

Yes, adding the 4th field to "allow_empty_fields" fixes it.

**Comment by qaxi** [comment]
Hello,

mark as soved by commit a6b8573359ed11c8ca2d39f177c2d5fae5d8eb11 and release 1.0.10 by ce7352bf86677852d00d29519d683b738de7c698

Add compatibility with Cisco Catalyst C1300 by solving this issue #79 thanx to @alexandrud .

I added mentions about compatibility of the whole C1300 series in documentation and galaxy.xml, but adding "C1300-24T-4G" as supported switch I would need write unit tests (anyone to volunteer? ;-) )

Thanks for help, very appreciated.
